# Generated by Django 4.1.2 on 2022-10-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Концерн',
                'verbose_name_plural': 'Концерны',
            },
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Автосалон',
                'verbose_name_plural': 'Автосалоны',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25, verbose_name='Бренд')),
                ('engine', models.CharField(max_length=25, verbose_name='Двигатель')),
                ('year', models.IntegerField(null=True, verbose_name='Год сборки')),
                ('color', models.CharField(max_length=15, null=True, verbose_name='Цвет')),
                ('concern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.concern', verbose_name='Концерн')),
                ('showroom', models.ManyToManyField(blank=True, null=True, to='crud.showroom', verbose_name='Автосалон')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
