# Generated by Django 4.1.2 on 2022-10-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('бензин', 'бензин'), ('дизель', 'дизель'), ('газ', 'газ'), ('гибрид', 'гибрид')], max_length=25, verbose_name='Двигатель'),
        ),
    ]
